### ISSUE TITLE
v6.0.7 书签脚本执行 js 时的作用域问题

### ISSUE THREAD

**Issue by g8up** [shuax/GreenChrome#14]
通过书签执行js时，官方原版是在当前页面执行 js。而 GreenChrome 却会新建一个 tab 再执行。

调试方法：
把以下脚本保存为书签，并点击执行，查看弹出窗口显示的地址是不是当前页面：

> javascript:void((function(){alert(window.location.href);})());

官方版本弹出的是当前页面的地址，GreenChrome 弹出的是 about:blank

**Comment by shuax** [comment]
新标签打开书签
　　点击书签在新标签中打开，不支持文件夹中的书签，不支持特殊功能书签

特殊的意思就是js之类的书签

**Comment by g8up** [comment]
了解。Thx~
