### ISSUE TITLE
Chrome版本太旧这个提示有没有办法干掉？

### ISSUE THREAD

**Issue by luantu** [shuax/GreenChrome#15]
类似这个http://imgsrc.baidu.com/forum/w%3D580/sign=d0ac149feef81a4c2632ecc1e72b6029/7241a899a9014c08b2998e4e0f7b02087af4f425.jpg
由于要用mactype渲染，停留在了51的版本。跪求大神研究下这个是否有破解之道。

**Comment by shuax** [comment]
添加启动参数
`--disable-background-networking`
试试

**Comment by luantu** [comment]
--disable-background-networking 似乎会把谷歌账号相关同步也都给干掉了。。

**Comment by shuax** [comment]
那就不会别的了
