### ISSUE TITLE
请教个特定条件下添加参数的功能

### ISSUE THREAD

**Issue by bstaint** [shuax/GreenChrome#2]
请教个问题，我想实现直接执行chrome是正常打开，如果点击一些软件上的链接使用隐身模式打开，原来gcc的时候自己改下没问题，现在改成vs就没辙了，请教下作者有什么建议么。

**Comment by shuax** [comment]
改成vs只是引导变了，别的地方没变啊。你可能需要判断是不是explorer打开的chrome。

**Comment by bstaint** [comment]
好吧，谢了。
