### ISSUE TITLE
2.2版无法启用NPAPI

### ISSUE THREAD

**Issue by vivahu** [shuax/GreenChrome#3]
Chrome版本号：47.0.2526.106 (64-bit)
GreenChrome版本号：2.2
操作系统版本：Windows 7 (64-bit)

GreenChrome已设置“恢复NPAPI”，但是访问招行网银时，安装控件后仍然无法输入密码。

**Comment by vivahu** [comment]
与作者联系上了，恢复NPAPI只支持32-bit的Chrome，而且原因是因为大部分NPAPI插件只有32bit版，与GreenChrome无关。GreenChrome的32位、64位功能完全一样。

**Comment by shuax** [comment]
并不是恢复npapi只支持32位，而是没几个支持64位的npapi插件。
