### ISSUE TITLE
功能需求：允许并非来自 Chrome 网上应用店的扩展

### ISSUE THREAD

**Issue by myfreeer** [shuax/GreenChrome#5]
即重启后不自动禁用，以及禁用扩展computed_hashes.json防修改功能

**Comment by shuax** [comment]
好像有个组策略工具

**Comment by myfreeer** [comment]
reg add hklm\Software\Policies\Google\Chrome\ExtensionInstallForcelist /v 1
/d egbmicdackhkbablgolioknjnklpaioo; /f
reg add hklm\Software\Policies\Chromium\ExtensionInstallWhitelist /v 1 /d
egbmicdackhkbablgolioknjnklpaioo /f
reg add hklm\Software\Policies\Google\Chrome\ExtensionInstalWhitelist /v 1
/d egbmicdackhkbablgolioknjnklpaioo /f
这几个都试过，不可用

另外，能否禁用扩展computed_hashes.json防修改功能

50.0.2661.102stable

2016-05-17 16:46 GMT+08:00 舒俊杰 <notifications@github.com>:

**Comment by shuax** [comment]
不是注册表，是组策略

**Comment by myfreeer** [comment]
那样就不能静默修改，也就是设置不能便携化了

2016-05-18 23:13 GMT+08:00 舒俊杰 <notifications@github.com>:
