### ISSUE TITLE
Win10无法设置为默认浏览器

### ISSUE THREAD

**Issue by vempx** [shuax/GreenChrome#9]
在Win10 64bit下面，无法保存设置默认浏览器为Chrome，请问有什么办法吗？

**Comment by shuax** [comment]
可以的啊。

**Comment by vempx** [comment]
我这边是把Chrome的安装包里面的7z解压出来，然后加载GreenChrome使用的。
Chrome的设置中始终说不是默认浏览器，然后点击将Chrome设置为默认浏览器按钮会自动弹出Win10的默认应用设置，浏览器那里选择Chrome没有效果，仍旧是空的。

**Comment by vempx** [comment]
哦……我又试了一下，不管是选Edge还是IE都选不上，看来是我系统的问题……不好意思……orz
